### ISSUE TITLE
usage: ipykernel_launcher.py [-h] [--ip IP] [--port PORT] ipykernel_launcher.py: error: unrecognized arguments: -f C:\Users\gassim khalid\AppData\Roaming\jupyter\runtime\kernel-a4fb2bb6-4179-4837-b273-da5f5c16e8d6.json

### ISSUE THREAD

**Issue by Mkay1999** [krpouncy/PyMuse#3]
I have tried streaming eeg data through muse monitor but ran into the following ( error usage: ipykernel_launcher.py [-h] [--ip IP] [--port PORT]
ipykernel_launcher.py: error: unrecognized arguments: -f C:\Users\gassim khalid\AppData\Roaming\jupyter\runtime\kernel-a4fb2bb6-4179-4837-b273-da5f5c16e8d6.json)

I have seen that this issue was raised before but the fix didn't work for me please let me know if you have found an alternative way to fix this. Thank you in advance

**Comment by krpouncy** [comment]
Hi Mkay1999,

This looks like an "argparse" issue with Jupyter Notebook.
A quick fix is go into PyMuse.py and add 'args=[]' in the line "args = parser.parse_args()". I will also update the code in the repository.
`args = parser.parse_args(args = [])`

At the moment, PyMuse doesn't work so well with Jupyter Notebook because the server is blocking and executes forever. You would have to make it [Async](https://python-osc.readthedocs.io/en/latest/server.html#concurrent-mode), so you can run other lines of code in Jupyter. Sorry for the inconvenience.
